### ISSUE TITLE
Camera image capture problem. 

### ISSUE THREAD

**Issue by faizan321** [Tofira/ImagePickerWithCrop#2]
Gallery image picker working fine, but camera intent open capture the picture , picture also save in directory but now show on imageview. and also not receiving the directory path.

**Comment by Tofira** [comment]
Hi,

What kind of phone are you using? which Android version?
Are you getting a URI back from the callback listener?

**Comment by intrepidkarthi** [comment]
@Tofira URI is not received on Marshmallow on Samsung S7 mobile. Is there any solution on that?

**Comment by intrepidkarthi** [comment]
@Tofira Receiving `onActivityResult(int requestCode, int resultCode, Intent data)` resultCode as -1 inside TempActivity

**Comment by Tofira** [comment]
I'll look into both cases and hopefully push an update soon.

**Comment by Tofira** [comment]
Oh sorry you're referring to the original issue.

**Comment by faizan321** [comment]
i can not receive the URL and i am using Samsung S5(Marshmallow) and LG-G5(Marshmallow).

**Comment by faizan321** [comment]
i Receive the gallery image URL but can not receive the Camera image URL

**Comment by faizan321** [comment]
i have also test it on Samsung S5 (5.0) and got same result. please provide the solution if possible.

**Comment by Tofira** [comment]
@faizan321 ,I've pushed an update, should be fixed now (tested with Galaxy S7).

**Comment by faizan321** [comment]
now its working great. Thank you so much.
