### ISSUE TITLE
Allow to select image from both gallery and camera

### ISSUE THREAD

**Issue by RiccardoMoro** [Tofira/ImagePickerWithCrop#4]
Hi, nice library, I'm currently using it in my applications!

But it's missing a key feature I need, which is the option to pick an image from gallery AND camera.

Thanks, RIccardo

**Comment by elfatah** [comment]
`just use  PickerBuilder.SELECT_FROM_CAMERA to pick from camera and  PickerBuilder.SELECT_FROM_GALLERY to pick from gallery in the picker builder

**Comment by Tofira** [comment]
You can use the following code to prompt the user to choose between camera or gallery with a basic Dialog - 
Insert the following in `PickerBuilder` - 

    public interface PickerBuilderCallbacks {
        void onImageUriReceived(Uri imageUri, int fromWhere);
    }
    public static void showDialog(final Activity activity, final PickerBuilderCallbacks pickerBuilderCallbacks)
    {
        new AlertDialog.Builder(activity)
                .setTitle(R.string.pick_image_title)
                .setMessage(R.string.pick_image_msg)
                .setCancelable(true)
                .setPositiveButton(R.string.open_camera, new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int which) {
                        getImage(activity,pickerBuilderCallbacks, PickerBuilder.SELECT_FROM_CAMERA);
                    }
                })
                .setNegativeButton(R.string.open_gallery, new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int which) {
                        getImage(activity,pickerBuilderCallbacks,PickerBuilder.SELECT_FROM_GALLERY);
                    }
                })
                .show();
    }
    private static void getImage(final Activity activity, final PickerBuilderCallbacks pickerBuilderCallbacks , final int fromWhere)
    {
        new PickerBuilder(activity, fromWhere)
                .setOnImageReceivedListener(new PickerBuilder.onImageReceivedListener() {
                    @Override
                    public void onImageReceived(Uri imageUri) {
                        pickerBuilderCallbacks.onImageUriReceived(imageUri, fromWhere);
                    }
                })
                .setImageName(activity.getString(R.string.app_name))
                .setImageFolderName(null)
                .withTimeStamp(false)
                .start();
    }

Then you can use it as such - 
```
PickerBuilder.showDialog(this, new PickerBuilder.PickerBuilderCallbacks() {
    @Override
    public void onImageUriReceived(Uri imageUri, int fromWhere) {
        Bitmap bitmap = BitmapHelper.decodeUriFixRotation(getBaseContext(),fromWhere,imageUri);
        setupNewImage(bitmap);
    }
});
```

Note, that `fromWhere` indicates if the image was received from the camera or the gallery.

**Comment by RiccardoMoro** [comment]
Thank you for the answer
I was wandering if it's possible to make like a PickerBuilder.SELECT_FROM_CAMERA_OR_GALLERY type and within the android application chooser let the user choose between gallery and camera apps all together.
For now I will make a dialog as you suggested, maybe when I'll have time I will make a pull request with this feature.
Thanks a lot for answering.
